name: JW TEST
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name : install numpy
      run : pip3 install numpy
    - name : test2
      run: python test_1.py
    - name : test1
      run : python test_2.py
